spring.application.name=plenamente

# cambiar el nombre de la bd
spring.datasource.url=jdbc:mysql://localhost:3306/plenamente_bd?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=

# Importante: Esto creará las tablas de tu diagrama automáticamente
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true